"""
Generate a folder skeleton for solving every problem in problems.json.

Layout produced under ./solutions/ (configurable via --root):

    solutions/
        step_01_learn_the_basics/
            lecture_01_things_to_know/
                001_input-output/
                    solution.cpp     ← C++ stub, only created if missing
                    README.md        ← links to article / video / practice

`solution.cpp` is NEVER overwritten if it already exists — that protects your
in-progress work. `README.md` is rewritten on every run so the links stay
fresh as the source sheet evolves.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


HERE = Path(__file__).parent
DEFAULT_PROBLEMS = HERE / "problems.json"
DEFAULT_ROOT = HERE / "solutions"

_SLUG_RE = re.compile(r"[^a-zA-Z0-9]+")


def _slugify(s: str) -> str:
    return _SLUG_RE.sub("-", s).strip("-").lower() or "untitled"


def _step_dir_name(step: dict[str, Any]) -> str:
    return f"step_{step['step_no']:02d}_{_slugify(step['step_title'])[:40]}"


def _lecture_dir_name(lec: dict[str, Any]) -> str:
    return f"lecture_{lec['lecture_no']:02d}_{_slugify(lec['lecture_title'])[:40]}"


def _problem_dir_name(idx: int, problem: dict[str, Any]) -> str:
    slug = problem.get("slug") or _slugify(problem["title"])
    return f"{idx:03d}_{slug}"


_CPP_STUB = """// {title}
// Difficulty: {difficulty}
// {article_url}
// Generated by generate_skeleton.py — only created on first run.
#include <bits/stdc++.h>
using namespace std;

int main() {{
    // TODO: solve
    return 0;
}}
"""


def _cpp_stub(problem: dict[str, Any]) -> str:
    return _CPP_STUB.format(
        title=problem["title"],
        difficulty=problem.get("difficulty") or "?",
        article_url=problem.get("article_url") or "",
    )


def _readme(problem: dict[str, Any], step_title: str, lecture_title: str) -> str:
    lines = [
        f"# {problem['title']}",
        "",
        f"- **Step**: {step_title}",
        f"- **Lecture**: {lecture_title}",
        f"- **Difficulty**: {problem.get('difficulty') or 'Unknown'}",
        f"- **Problem ID**: {problem.get('id')}",
        f"- **Slug**: `{problem.get('slug')}`",
        "",
        "## Links",
        "",
    ]
    link_fields = [
        ("Article", "article_url"),
        ("YouTube", "youtube_url"),
        ("Practice (external)", "practice_url"),
        ("Plus problem", "plus_problem_url"),
        ("Plus editorial", "plus_editorial_url"),
    ]
    for label, key in link_fields:
        url = problem.get(key)
        if url:
            lines.append(f"- [{label}]({url})")
    lines.append("")
    return "\n".join(lines)


def generate(problems_path: Path, root: Path, *, force_cpp: bool = False) -> tuple[int, int]:
    """Create the folder layout. Returns (new_cpp_files, total_problems)."""
    data = json.loads(problems_path.read_text(encoding="utf-8"))
    new_cpp = 0
    total = 0
    for step in data["steps"]:
        step_dir = root / _step_dir_name(step)
        for lec in step["lectures"]:
            lec_dir = step_dir / _lecture_dir_name(lec)
            for idx, problem in enumerate(lec["problems"], start=1):
                total += 1
                p_dir = lec_dir / _problem_dir_name(idx, problem)
                p_dir.mkdir(parents=True, exist_ok=True)
                cpp = p_dir / "solution.cpp"
                if force_cpp or not cpp.exists():
                    cpp.write_text(_cpp_stub(problem), encoding="utf-8")
                    new_cpp += 1
                (p_dir / "README.md").write_text(
                    _readme(problem, step["step_title"], lec["lecture_title"]),
                    encoding="utf-8",
                )
    return new_cpp, total


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--problems",
        type=Path,
        default=DEFAULT_PROBLEMS,
        help=f"problems JSON path (default: {DEFAULT_PROBLEMS.name})",
    )
    p.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help=f"root directory for generated folders (default: {DEFAULT_ROOT.name})",
    )
    p.add_argument(
        "--force-cpp",
        action="store_true",
        help="overwrite existing solution.cpp files (DANGEROUS — destroys work)",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if not args.problems.exists():
        print(f"! {args.problems} not found — run scrape_takeuforward.py first", file=sys.stderr)
        return 1
    new_cpp, total = generate(args.problems, args.root, force_cpp=args.force_cpp)
    print(f"· {total} problems, {new_cpp} new solution.cpp files under {args.root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
